### ISSUE TITLE
Payload too large error for file sizes < 10MB

### ISSUE THREAD

**Issue by FadyMak** [auth0/auth0-user-import-export-extension#8]
Getting a 413 Payload too large error when importing a file containing users with <10MB size (i.e.: 2MB, 5MB, etc...).

Error:

```
Error: request entity too large
   at makeError (/data/_verquire/body-parser/1.12.4/node_modules/raw-body/index.js:154:15)
   at readStream (/data/_verquire/body-parser/1.12.4/node_modules/raw-body/index.js:188:15)
   at getRawBody (/data/_verquire/body-parser/1.12.4/node_modules/raw-body/index.js:95:12)
   at read (/data/_verquire/body-parser/1.12.4/node_modules/body-parser/lib/read.js:64:3)
   at jsonParser (/data/_verquire/body-parser/1.12.4/node_modules/body-parser/lib/types/json.js:116:5)
   at Layer.handle [as handle_request] (/data/_verquire/express/4.12.4/node_modules/express/lib/router/layer.js:82:5)
   at trim_prefix (/data/_verquire/express/4.12.4/node_modules/express/lib/router/index.js:302:13)
   at /data/_verquire/express/4.12.4/node_modules/express/lib/router/index.js:270:7
   at Function.proto.process_params (/data/_verquire/express/4.12.4/node_modules/express/lib/router/index.js:321:12)
   at next (/data/_verquire/express/4.12.4/node_modules/express/lib/router/index.js:261:10)
```

**Comment by sandrinodimattia** [comment]
The issue with the extension has been fixed, please update to 1.6

Now the Auth0 Management API also has some issues with large files, please follow up there.
